version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint JS
          command: yarn lint:js
      - run:
          name: Lint CSS
          command: yarn lint:css
      - run:
          name: Flow
          command: yarn flow check
      - run:
          name: Run Tests
          command: yarn test --coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
