version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint CSS
          command: yarn lint:js
      - run:
          name: Lint CSS
          command: yarn lint:css
      - run:
          name: Tests
          command: yarn test --coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
